### ISSUE TITLE
Next.js example host not working as expected

### ISSUE THREAD

**Issue by amaralc** [tiny-frontend/example-host-nextjs#4]
Hello @adrienbaron, I noticed that the SSR and Client tiny frontends are not working as expected in the following link: https://example-host-nextjs.vercel.app/

The styles are not loading and nothing happens when I click in the button.

SSR
![image](https://user-images.githubusercontent.com/32170099/175824056-13937553-9f4b-46ec-884b-301b1d6d0eea.png)

Client
![image](https://user-images.githubusercontent.com/32170099/175824167-acb217f7-8eb1-452e-8ef2-907f094d0274.png)

I don't know exactly how to help since I was trying to learn how to use it, but I hope opening the issue was a good start.

**Comment by adrienbaron** [comment]
Hey! Thank you for the shout! I'll have a look when I get home 😊.
The Remix example seems to work for now though: https://tiny-frontend-example-host-remix.fly.dev

**Comment by amaralc** [comment]
Yes, the remix example was working properly, I forgot to mention. Oh, just some more information... When I clone the next host repository and run it locally, everything works perfectly.

![image](https://user-images.githubusercontent.com/32170099/175824437-ef8e4f1c-0205-4b24-bea5-c283314c7f98.png)

**Comment by adrienbaron** [comment]
Sorry ended up having a busy Sunday and not finding time to have a proper look, I'll set a reminder for tomorrow 👍

**Comment by adrienbaron** [comment]
@amaralc this should now be fixed by [this commit](https://github.com/tiny-frontend/example-host-nextjs/commit/c40e4da67855be8b162714e8e729f87cb3020a55) 🎉!
Issue was that this app was still using an old version of the contract and bundle for it had gotten deleted from Cloudflare.

**Comment by adrienbaron** [comment]
@amaralc spoke too fast, I found the actual issue, Next was a bit too smart and building this example app as a static page, which was hardcoding the remote bundle for the tiny frontend in the page.
I fixed it by forcing [Next to always SSR](https://github.com/tiny-frontend/example-host-nextjs/pull/5).

You might not need that if you want to only load the tiny frontend client side 👍

**Comment by amaralc** [comment]
Thanks for the reply @adrienbaron! In my case I will need to use the SSR so it will be fine since I have already defined the getServerSideProps, or getStaticProps in these situations.

**Comment by amaralc** [comment]
Fixed by #5
